from __future__ import annotations

"""
Apply a scheduled active-sensing plan to the truth trajectory.

Redesign notes:
- Supports multi-impulse schedules generated by the new Experiment III planner.
- Backward-compatible with older single-impulse plan CSVs.
- Uses piecewise propagation with repeated observer micro-impulses.
"""

from pathlib import Path
import argparse
import sys

import numpy as np
import pandas as pd

THIS_FILE = Path(__file__).resolve()
SIM_DIR = THIS_FILE.parent
PROJECT_ROOT = SIM_DIR.parent
for _p in [PROJECT_ROOT, SIM_DIR, PROJECT_ROOT / "pipeline"]:
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)

try:
    import config  # type: ignore
except Exception:
    config = None  # type: ignore

try:
    from core_orekit_sim import (
        UTC,
        EME2000,
        MU,
        build_numerical_propagator,
        apply_impulse_rtn,
        to_rtn_relative,
        add_future_labels,
    )
except Exception:
    try:
        from sim.core_orekit_sim import (
            UTC,
            EME2000,
            MU,
            build_numerical_propagator,
            apply_impulse_rtn,
            to_rtn_relative,
            add_future_labels,
        )
    except Exception:
        from ore.sim.core_orekit_sim import (
            UTC,
            EME2000,
            MU,
            build_numerical_propagator,
            apply_impulse_rtn,
            to_rtn_relative,
            add_future_labels,
        )

from org.hipparchus.geometry.euclidean.threed import Vector3D
from org.orekit.utils import PVCoordinates
from org.orekit.time import AbsoluteDate
from org.orekit.orbits import CartesianOrbit
from org.orekit.propagation import SpacecraftState

START_DATE = AbsoluteDate(2026, 3, 24, 0, 0, 0.0, UTC)
CHASER_MASS_KG = 250.0
TARGET_DEFAULT_MASS_KG = 180.0

DEFAULT_ORIG_TRUTH = Path(r"D:\robot_view\ore\dataset_rtn\val\no_maneuver\sample_00400.csv")
DEFAULT_PLAN_CSV = Path(r"D:\robot_view\ore\mc_consistency_test\micro_dv_plan.csv")
DEFAULT_OUT_TRUTH = Path(r"D:\robot_view\ore\dataset_active\sample_00400_active.csv")
TIMING_SEMANTICS = "step_begin_post_impulse_sample"


def _parquet_path(path: Path) -> Path:
    if path.suffix.lower() == ".parquet":
        return path
    return path.with_suffix(".parquet")


def read_table(path: Path, *, use_parquet: bool = False) -> pd.DataFrame:
    if use_parquet:
        pq_path = _parquet_path(path)
        if pq_path.exists():
            try:
                return pd.read_parquet(pq_path)
            except Exception as exc:
                print(f"[WARN] failed to read parquet {pq_path}: {exc}; fallback to CSV")
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path)


def write_table(df: pd.DataFrame, path: Path, *, use_parquet: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if use_parquet:
        pq_path = _parquet_path(path)
        try:
            df.to_parquet(pq_path, index=False, engine="pyarrow")
        except Exception as exc:
            print(f"[WARN] failed to write parquet {pq_path}: {exc}; CSV output is kept")
    df.to_csv(path, index=False, encoding="utf-8-sig")


def state_from_components(
    r_xyz: tuple[float, float, float],
    v_xyz: tuple[float, float, float],
    date,
    mass_kg: float,
) -> SpacecraftState:
    r = Vector3D(float(r_xyz[0]), float(r_xyz[1]), float(r_xyz[2]))
    v = Vector3D(float(v_xyz[0]), float(v_xyz[1]), float(v_xyz[2]))
    orbit = CartesianOrbit(PVCoordinates(r, v), EME2000, date, MU)
    return SpacecraftState(orbit, float(mass_kg))


def state_from_row(row: pd.Series, date, which: str = "chaser") -> SpacecraftState:
    if which == "chaser":
        return state_from_components(
            (float(row["rc_x_m"]), float(row["rc_y_m"]), float(row["rc_z_m"])),
            (float(row["vc_x_mps"]), float(row["vc_y_mps"]), float(row["vc_z_mps"])),
            date,
            CHASER_MASS_KG,
        )
    elif which == "target":
        mass = float(row["target_mass_kg"]) if "target_mass_kg" in row else TARGET_DEFAULT_MASS_KG
        return state_from_components(
            (float(row["rt_x_m"]), float(row["rt_y_m"]), float(row["rt_z_m"])),
            (float(row["vt_x_mps"]), float(row["vt_y_mps"]), float(row["vt_z_mps"])),
            date,
            mass,
        )
    else:
        raise ValueError("which must be 'chaser' or 'target'")


def propagate_to(state: SpacecraftState, t_sec: float) -> SpacecraftState:
    prop = build_numerical_propagator(state, integ_step_s=1.0)
    return prop.propagate(START_DATE.shiftedBy(float(t_sec)))


def build_row_from_states(t_sec: float, chaser_state: SpacecraftState, target_state: SpacecraftState,
                          applied_dv: np.ndarray | None) -> dict:
    ch_pv = chaser_state.getPVCoordinates()
    tg_pv = target_state.getPVCoordinates()
    rc = ch_pv.getPosition(); vc = ch_pv.getVelocity()
    rt = tg_pv.getPosition(); vt = tg_pv.getVelocity()
    R, T, N, dR, dT, dN = to_rtn_relative(chaser_state, target_state)
    dist = rt.subtract(rc).getNorm()
    observer_flag = 1 if applied_dv is not None else 0
    dv = np.zeros(3, dtype=float) if applied_dv is None else np.asarray(applied_dv, dtype=float)
    return {
        "t_sec": float(t_sec),
        "rc_x_m": rc.getX(), "rc_y_m": rc.getY(), "rc_z_m": rc.getZ(),
        "vc_x_mps": vc.getX(), "vc_y_mps": vc.getY(), "vc_z_mps": vc.getZ(),
        "rt_x_m": rt.getX(), "rt_y_m": rt.getY(), "rt_z_m": rt.getZ(),
        "vt_x_mps": vt.getX(), "vt_y_mps": vt.getY(), "vt_z_mps": vt.getZ(),
        "rel_R_m": R, "rel_T_m": T, "rel_N_m": N,
        "rel_dR_mps": dR, "rel_dT_mps": dT, "rel_dN_mps": dN,
        "relative_distance_m": dist,
        "target_mass_kg": target_state.getMass(),
        "maneuver_flag": 0,
        "maneuver_type": "none",
        "observer_maneuver_flag": observer_flag,
        "observer_maneuver_type": "active_sensing_scheduled_micro_dv" if observer_flag else "none",
        "observer_dv_R_mps": float(dv[0]) if observer_flag else 0.0,
        "observer_dv_T_mps": float(dv[1]) if observer_flag else 0.0,
        "observer_dv_N_mps": float(dv[2]) if observer_flag else 0.0,
        "timing_semantics": TIMING_SEMANTICS,
    }


def _canonical_time_key(t_sec: float) -> float:
    return float(round(float(t_sec), 9))


def parse_schedule(plan_df: pd.DataFrame, strategy: str = "robust") -> tuple[list[float], list[np.ndarray]]:
    if "strategy" in plan_df.columns:
        use = plan_df[plan_df["strategy"].astype(str).str.lower() == strategy.lower()].copy()
    else:
        use = plan_df.copy()
    if len(use) == 0:
        raise RuntimeError(f"No rows were found for strategy='{strategy}' in plan csv.")

    if "step_index" in use.columns:
        use = use.sort_values(["apply_t_sec", "step_index"]).reset_index(drop=True)
    else:
        use = use.sort_values(["apply_t_sec"]).reset_index(drop=True)

    n_rows = len(use)
    dv_r = use["dv_R_mps"].to_numpy(dtype=float) if "dv_R_mps" in use.columns else np.zeros(n_rows, dtype=float)
    dv_t = use["dv_T_mps"].to_numpy(dtype=float) if "dv_T_mps" in use.columns else np.zeros(n_rows, dtype=float)
    dv_n = use["dv_N_mps"].to_numpy(dtype=float) if "dv_N_mps" in use.columns else np.zeros(n_rows, dtype=float)
    has_apply_t = "apply_t_sec" in use.columns
    has_trigger_t = "trigger_t_sec" in use.columns
    apply_t_values = use["apply_t_sec"].to_numpy(dtype=float) if has_apply_t else None
    trigger_t_values = use["trigger_t_sec"].to_numpy(dtype=float) if has_trigger_t else np.zeros(n_rows, dtype=float)

    times, dvs = [], []
    for idx in range(n_rows):
        dv = np.array([dv_r[idx], dv_t[idx], dv_n[idx]], dtype=float)
        if np.linalg.norm(dv) < 1e-12:
            continue
        apply_t = apply_t_values[idx] if has_apply_t else trigger_t_values[idx]
        times.append(_canonical_time_key(apply_t))
        dvs.append(dv)
    if len(times) == 0:
        trigger_t = _canonical_time_key(trigger_t_values[0] if has_trigger_t else 0.0)
        times = [trigger_t]
        dvs = [np.zeros(3, dtype=float)]
    return times, dvs


def validate_schedule_alignment(plan_df: pd.DataFrame, orig_df: pd.DataFrame, times: list[float]) -> None:
    if "rollout_timing_semantics" in plan_df.columns:
        semantics = plan_df["rollout_timing_semantics"].astype(str).str.strip()
        bad_values = sorted({v for v in semantics.tolist() if v and v != TIMING_SEMANTICS})
        if bad_values:
            raise RuntimeError(
                "rollout_timing_semantics mismatch: "
                f"expected '{TIMING_SEMANTICS}', got {bad_values}"
            )

    if "t_sec" not in orig_df.columns:
        raise RuntimeError("orig truth csv is missing t_sec; cannot validate schedule alignment")
    all_times = orig_df["t_sec"].to_numpy(dtype=float)
    if all_times.size < 2:
        raise RuntimeError("orig truth csv must have at least two rows for timing validation")

    dt = float(all_times[1] - all_times[0])
    tol = max(1.0e-9, 1.0e-6 * max(1.0, abs(dt)))

    if "trigger_t_sec" in plan_df.columns:
        trigger_t = float(plan_df["trigger_t_sec"].iloc[0])
        if np.min(np.abs(all_times - trigger_t)) > tol:
            raise RuntimeError(
                f"trigger_t_sec={trigger_t:.6f} is not on truth time grid (dt={dt:.6f})"
            )

    for at in times:
        if np.min(np.abs(all_times - float(at))) > tol:
            raise RuntimeError(
                f"apply_t_sec={float(at):.6f} is not on truth time grid (dt={dt:.6f})"
            )


def apply_plan_to_truth(
    orig_truth_csv: Path,
    plan_csv: Path,
    out_truth_csv: Path,
    strategy: str = "robust",
    use_parquet: bool = False,
) -> pd.DataFrame:
    # Unified semantics with planner/preview: sample each row at step-begin
    # after applying any impulse scheduled for that timestamp.
    orig_df = read_table(orig_truth_csv, use_parquet=use_parquet)
    plan_df = read_table(plan_csv, use_parquet=use_parquet)

    times, dvs = parse_schedule(plan_df, strategy=strategy)
    validate_schedule_alignment(plan_df, orig_df, times)
    all_times = orig_df["t_sec"].to_numpy(dtype=float)

    time_to_dvs: dict[float, list[np.ndarray]] = {}
    for at, dv in zip(times, dvs):
        time_to_dvs.setdefault(_canonical_time_key(at), []).append(np.asarray(dv, dtype=float))

    t_values = orig_df["t_sec"].to_numpy(dtype=float)
    rc_x = orig_df["rc_x_m"].to_numpy(dtype=float)
    rc_y = orig_df["rc_y_m"].to_numpy(dtype=float)
    rc_z = orig_df["rc_z_m"].to_numpy(dtype=float)
    vc_x = orig_df["vc_x_mps"].to_numpy(dtype=float)
    vc_y = orig_df["vc_y_mps"].to_numpy(dtype=float)
    vc_z = orig_df["vc_z_mps"].to_numpy(dtype=float)
    rt_x = orig_df["rt_x_m"].to_numpy(dtype=float)
    rt_y = orig_df["rt_y_m"].to_numpy(dtype=float)
    rt_z = orig_df["rt_z_m"].to_numpy(dtype=float)
    vt_x = orig_df["vt_x_mps"].to_numpy(dtype=float)
    vt_y = orig_df["vt_y_mps"].to_numpy(dtype=float)
    vt_z = orig_df["vt_z_mps"].to_numpy(dtype=float)

    has_target_mass = "target_mass_kg" in orig_df.columns
    target_mass_values = orig_df["target_mass_kg"].to_numpy(dtype=float) if has_target_mass else None
    has_maneuver_flag = "maneuver_flag" in orig_df.columns
    maneuver_flag_values = orig_df["maneuver_flag"].to_numpy() if has_maneuver_flag else None
    has_maneuver_type = "maneuver_type" in orig_df.columns
    maneuver_type_values = orig_df["maneuver_type"].to_numpy(dtype=object) if has_maneuver_type else None

    current_t = float(t_values[0])
    current_ch = state_from_components(
        (rc_x[0], rc_y[0], rc_z[0]),
        (vc_x[0], vc_y[0], vc_z[0]),
        START_DATE.shiftedBy(current_t),
        CHASER_MASS_KG,
    )

    rows = []
    tol = 1e-9

    for idx in range(t_values.shape[0]):
        t = float(t_values[idx])

        # 先把 observer 传播到当前采样时刻
        if current_t < t - tol:
            current_ch = build_numerical_propagator(current_ch, integ_step_s=1.0).propagate(
                START_DATE.shiftedBy(t)
            )
            current_t = t

        # target 不重新传播，直接使用原 truth 在该时刻的状态
        target_mass = float(target_mass_values[idx]) if has_target_mass else TARGET_DEFAULT_MASS_KG
        current_tg = state_from_components(
            (rt_x[idx], rt_y[idx], rt_z[idx]),
            (vt_x[idx], vt_y[idx], vt_z[idx]),
            START_DATE.shiftedBy(t),
            target_mass,
        )

        # 若该采样时刻有计划脉冲，则在该时刻施加（step-begin 语义）
        applied_dv = None
        t_key = _canonical_time_key(t)
        if t_key in time_to_dvs:
            dv_sum = np.zeros(3, dtype=float)
            for dv in time_to_dvs[t_key]:
                current_ch = apply_impulse_rtn(current_ch, dv.tolist(), isp_s=None, mu=MU)
                dv_sum += dv
            applied_dv = dv_sum

        row = build_row_from_states(t, current_ch, current_tg, applied_dv)

        # 保留原始 truth 中目标机动标记
        row["maneuver_flag"] = int(maneuver_flag_values[idx]) if has_maneuver_flag else 0
        row["maneuver_type"] = str(maneuver_type_values[idx]) if has_maneuver_type else "none"
        row["target_mass_kg"] = target_mass if has_target_mass else row["target_mass_kg"]

        rows.append(row)

    out_df = pd.DataFrame(rows)
    out_df = add_future_labels(out_df, window_sec=300.0, danger_thr_m=200.0, caution_thr_m=1000.0)
    write_table(out_df, out_truth_csv, use_parquet=use_parquet)
    return out_df


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--orig_truth_csv", default=str(DEFAULT_ORIG_TRUTH))
    ap.add_argument("--plan_csv", default=str(DEFAULT_PLAN_CSV))
    ap.add_argument("--out_truth_csv", default=str(DEFAULT_OUT_TRUTH))
    ap.add_argument("--strategy", default="robust", choices=["robust", "nominal"])
    ap.add_argument("--use_parquet", action="store_true",
                    help="Read parquet sidecars when available and also export parquet sidecar outputs.")
    args = ap.parse_args()

    out_df = apply_plan_to_truth(
        Path(args.orig_truth_csv),
        Path(args.plan_csv),
        Path(args.out_truth_csv),
        strategy=args.strategy,
        use_parquet=bool(args.use_parquet),
    )
    print("===== Active Sensing Closed-loop Truth Generated =====")
    print("Original truth :", args.orig_truth_csv)
    print("Plan csv       :", args.plan_csv)
    print("Output truth   :", args.out_truth_csv)
    print("Strategy       :", args.strategy)
    print("Use parquet    :", bool(args.use_parquet))
    print("Rows           :", len(out_df))


if __name__ == "__main__":
    main()
